### PR TITLE
odh-7074-b and 7075   - qe comments

### PR DESCRIPTION
**Pull request by MelissaFlinn**
addressing QE comment for prereq of creating a workbench (7075)

### CODE REVIEW

**Review by jiridanek — APPROVED** [review]
This no longer creates the impression that using s3 and having the s3 credentials is mandatory.

/lgtm

**Comment by MelissaFlinn** [comment]
another commit - qe comment - remove duplicate paragraph (7074)

**Review by jiridanek — APPROVED** [review]
yes, thanks for the second change too!

**Review by eturner24 — APPROVED** [review]
Looks good to me!

**Pull request merged**
